package model;
// Generated 06/08/2018 21:12:34 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name="auditoria"
    ,schema="public"
)
public class Auditoria  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String ip;
     private String sql;
     private Date dataHora;

    public Auditoria() {
    }

    public Auditoria(int id, Usuario usuario, String ip, String sql, Date dataHora) {
       this.id = id;
       this.usuario = usuario;
       this.ip = ip;
       this.sql = sql;
       this.dataHora = dataHora;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="ip", nullable=false, length=50)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="sql", nullable=false)
    public String getSql() {
        return this.sql;
    }
    
    public void setSql(String sql) {
        this.sql = sql;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora", nullable=false, length=29)
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


