package model;
// Generated 10/08/2018 00:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import utils.ValidacaoException;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name = "cidade",
         schema = "public"
)
public class Cidade implements java.io.Serializable {

    private Integer id;
    private String nome;
    private boolean situacao;
    private Set pessoas = new HashSet(0);

    public Cidade() {
    }

    public Cidade(Integer id, String nome, boolean situacao) {
        this.id = id;
        this.nome = nome;
        this.situacao = situacao;
    }

    public Cidade(Integer id, String nome, boolean situacao, Set pessoas) {
        this.id = id;
        this.nome = nome;
        this.situacao = situacao;
        this.pessoas = pessoas;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "nome", nullable = false, length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "situacao", nullable = false)
    public boolean isSituacao() {
        return this.situacao;
    }

    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
    public Set getPessoas() {
        return this.pessoas;
    }

    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }
    
    public void validar() throws ValidacaoException{
        if(this.nome == null || this.nome.equals("")){
            throw new ValidacaoException("Campo nome não preenchido");
        }
            
        
    }

}
