package model;
// Generated Aug 13, 2018 9:27:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,schema="public"
)
public class Cidade implements java.io.Serializable {

    private long codCidade;
    private Estado estado;
    private String nome;
    private boolean situacao;
    private String cep;
    private Set pessoas = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(long codCidade, Estado estado, String nome, boolean situacao) {
        this.codCidade = codCidade;
        this.estado = estado;
        this.nome = nome;
        this.situacao = situacao;
    }
    public Cidade(long codCidade, Estado estado, String nome, boolean situacao, String cep, Set pessoas) {
       this.codCidade = codCidade;
       this.estado = estado;
       this.nome = nome;
       this.situacao = situacao;
       this.cep = cep;
       this.pessoas = pessoas;
    }
   

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="cod_cidade", unique=true, nullable=false)
    public long getCodCidade() {
        return this.codCidade;
    }
    
    public void setCodCidade(long codCidade) {
        this.codCidade = codCidade;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado_cod_estado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="situacao", nullable=false)
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


