package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classificacao generated by hbm2java
 */
public class Classificacao  implements java.io.Serializable {


     private int id;
     private String classificacao;
     private boolean situacao;
     private Set produtos = new HashSet(0);

    public Classificacao() {
    }

	
    public Classificacao(int id, String classificacao, boolean situacao) {
        this.id = id;
        this.classificacao = classificacao;
        this.situacao = situacao;
    }
    public Classificacao(int id, String classificacao, boolean situacao, Set produtos) {
       this.id = id;
       this.classificacao = classificacao;
       this.situacao = situacao;
       this.produtos = produtos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(String classificacao) {
        this.classificacao = classificacao;
    }
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


