package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ContasReceber generated by hbm2java
 */
public class ContasReceber  implements java.io.Serializable {


     private int id;
     private FormaPagamento formaPagamento;
     private Pedido pedido;
     private BigDecimal valorFinal;
     private Date dataPrevista;
     private Date dataPagamento;
     private BigDecimal desconto;
     private BigDecimal acrescimo;

    public ContasReceber() {
    }

	
    public ContasReceber(int id, FormaPagamento formaPagamento, Pedido pedido, BigDecimal valorFinal, Date dataPrevista) {
        this.id = id;
        this.formaPagamento = formaPagamento;
        this.pedido = pedido;
        this.valorFinal = valorFinal;
        this.dataPrevista = dataPrevista;
    }
    public ContasReceber(int id, FormaPagamento formaPagamento, Pedido pedido, BigDecimal valorFinal, Date dataPrevista, Date dataPagamento, BigDecimal desconto, BigDecimal acrescimo) {
       this.id = id;
       this.formaPagamento = formaPagamento;
       this.pedido = pedido;
       this.valorFinal = valorFinal;
       this.dataPrevista = dataPrevista;
       this.dataPagamento = dataPagamento;
       this.desconto = desconto;
       this.acrescimo = acrescimo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FormaPagamento getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(FormaPagamento formaPagamento) {
        this.formaPagamento = formaPagamento;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }
    public Date getDataPrevista() {
        return this.dataPrevista;
    }
    
    public void setDataPrevista(Date dataPrevista) {
        this.dataPrevista = dataPrevista;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }
    public BigDecimal getAcrescimo() {
        return this.acrescimo;
    }
    
    public void setAcrescimo(BigDecimal acrescimo) {
        this.acrescimo = acrescimo;
    }




}


