package model;
// Generated 06/08/2018 21:12:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cozinha generated by hbm2java
 */
@Entity
@Table(name="cozinha"
    ,schema="public"
)
public class Cozinha  implements java.io.Serializable {


     private int id;
     private int capacidade;

    public Cozinha() {
    }

    public Cozinha(int id, int capacidade) {
       this.id = id;
       this.capacidade = capacidade;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="capacidade", nullable=false)
    public int getCapacidade() {
        return this.capacidade;
    }
    
    public void setCapacidade(int capacidade) {
        this.capacidade = capacidade;
    }




}


