package model;
// Generated Aug 13, 2018 9:27:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,schema="public"
)
public class Estado  implements java.io.Serializable {


     private int codEstado;
     private String sigla;
     private String nome;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int codEstado, String sigla) {
        this.codEstado = codEstado;
        this.sigla = sigla;
    }
    public Estado(int codEstado, String sigla, String nome, Set cidades) {
       this.codEstado = codEstado;
       this.sigla = sigla;
       this.nome = nome;
       this.cidades = cidades;
    }
   
     @Id 

    
    @Column(name="cod_estado", unique=true, nullable=false)
    public int getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(int codEstado) {
        this.codEstado = codEstado;
    }

    
    @Column(name="sigla", nullable=false, length=2)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    
    @Column(name="nome", length=72)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


