package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPagamento generated by hbm2java
 */
public class FormaPagamento  implements java.io.Serializable {


     private int id;
     private String descricao;
     private int prazo;
     private Set contasRecebers = new HashSet(0);

    public FormaPagamento() {
    }

	
    public FormaPagamento(int id, String descricao, int prazo) {
        this.id = id;
        this.descricao = descricao;
        this.prazo = prazo;
    }
    public FormaPagamento(int id, String descricao, int prazo, Set contasRecebers) {
       this.id = id;
       this.descricao = descricao;
       this.prazo = prazo;
       this.contasRecebers = contasRecebers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getPrazo() {
        return this.prazo;
    }
    
    public void setPrazo(int prazo) {
        this.prazo = prazo;
    }
    public Set getContasRecebers() {
        return this.contasRecebers;
    }
    
    public void setContasRecebers(Set contasRecebers) {
        this.contasRecebers = contasRecebers;
    }




}


