package model;
// Generated 06/08/2018 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name="forma_pagamento"
    ,schema="public"
)
public class FormaPagamento  implements java.io.Serializable {


     private int id;
     private String descricao;
     private int prazo;
     private Set contasRecebers = new HashSet(0);

    public FormaPagamento() {
    }

	
    public FormaPagamento(int id, String descricao, int prazo) {
        this.id = id;
        this.descricao = descricao;
        this.prazo = prazo;
    }
    public FormaPagamento(int id, String descricao, int prazo, Set contasRecebers) {
       this.id = id;
       this.descricao = descricao;
       this.prazo = prazo;
       this.contasRecebers = contasRecebers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", nullable=false, length=150)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="prazo", nullable=false)
    public int getPrazo() {
        return this.prazo;
    }
    
    public void setPrazo(int prazo) {
        this.prazo = prazo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPagamento")
    public Set getContasRecebers() {
        return this.contasRecebers;
    }
    
    public void setContasRecebers(Set contasRecebers) {
        this.contasRecebers = contasRecebers;
    }




}


