package model;
// Generated 10/08/2018 00:28:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,schema="public"
)
public class Fornecedor  implements java.io.Serializable {


     private int id;
     private String nomeFantasia;
     private String razaoSocial;
     private String cnpj;
     private boolean situacao;
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int id, String nomeFantasia, boolean situacao) {
        this.id = id;
        this.nomeFantasia = nomeFantasia;
        this.situacao = situacao;
    }
    public Fornecedor(int id, String nomeFantasia, String razaoSocial, String cnpj, boolean situacao, Set produtos) {
       this.id = id;
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.cnpj = cnpj;
       this.situacao = situacao;
       this.produtos = produtos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome_fantasia", nullable=false, length=45)
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    
    @Column(name="razao_social", length=45)
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

    
    @Column(name="cnpj", length=14)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="situacao", nullable=false)
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


