package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int id;
     private String nomeFantasia;
     private String razaoSocial;
     private String cnpj;
     private boolean situacao;
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int id, String nomeFantasia, boolean situacao) {
        this.id = id;
        this.nomeFantasia = nomeFantasia;
        this.situacao = situacao;
    }
    public Fornecedor(int id, String nomeFantasia, String razaoSocial, String cnpj, boolean situacao, Set produtos) {
       this.id = id;
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.cnpj = cnpj;
       this.situacao = situacao;
       this.produtos = produtos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


