package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int id;
     private String descricao;
     private boolean moduloFinanceiro;
     private boolean moduloGestao;
     private boolean moduloCaixa;
     private boolean moduloCozinha;
     private boolean moduloAtendente;
     private boolean moduloAdmin;
     private Set usuarios = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int id, String descricao, boolean moduloFinanceiro, boolean moduloGestao, boolean moduloCaixa, boolean moduloCozinha, boolean moduloAtendente, boolean moduloAdmin) {
        this.id = id;
        this.descricao = descricao;
        this.moduloFinanceiro = moduloFinanceiro;
        this.moduloGestao = moduloGestao;
        this.moduloCaixa = moduloCaixa;
        this.moduloCozinha = moduloCozinha;
        this.moduloAtendente = moduloAtendente;
        this.moduloAdmin = moduloAdmin;
    }
    public Grupo(int id, String descricao, boolean moduloFinanceiro, boolean moduloGestao, boolean moduloCaixa, boolean moduloCozinha, boolean moduloAtendente, boolean moduloAdmin, Set usuarios) {
       this.id = id;
       this.descricao = descricao;
       this.moduloFinanceiro = moduloFinanceiro;
       this.moduloGestao = moduloGestao;
       this.moduloCaixa = moduloCaixa;
       this.moduloCozinha = moduloCozinha;
       this.moduloAtendente = moduloAtendente;
       this.moduloAdmin = moduloAdmin;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public boolean isModuloFinanceiro() {
        return this.moduloFinanceiro;
    }
    
    public void setModuloFinanceiro(boolean moduloFinanceiro) {
        this.moduloFinanceiro = moduloFinanceiro;
    }
    public boolean isModuloGestao() {
        return this.moduloGestao;
    }
    
    public void setModuloGestao(boolean moduloGestao) {
        this.moduloGestao = moduloGestao;
    }
    public boolean isModuloCaixa() {
        return this.moduloCaixa;
    }
    
    public void setModuloCaixa(boolean moduloCaixa) {
        this.moduloCaixa = moduloCaixa;
    }
    public boolean isModuloCozinha() {
        return this.moduloCozinha;
    }
    
    public void setModuloCozinha(boolean moduloCozinha) {
        this.moduloCozinha = moduloCozinha;
    }
    public boolean isModuloAtendente() {
        return this.moduloAtendente;
    }
    
    public void setModuloAtendente(boolean moduloAtendente) {
        this.moduloAtendente = moduloAtendente;
    }
    public boolean isModuloAdmin() {
        return this.moduloAdmin;
    }
    
    public void setModuloAdmin(boolean moduloAdmin) {
        this.moduloAdmin = moduloAdmin;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


