package model;
// Generated 06/08/2018 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name="grupo"
    ,schema="public"
)
public class Grupo  implements java.io.Serializable {


     private int id;
     private String descricao;
     private boolean moduloFinanceiro;
     private boolean moduloGestao;
     private boolean moduloCaixa;
     private boolean moduloCozinha;
     private boolean moduloAtendente;
     private boolean moduloAdmin;
     private Set usuarios = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int id, String descricao, boolean moduloFinanceiro, boolean moduloGestao, boolean moduloCaixa, boolean moduloCozinha, boolean moduloAtendente, boolean moduloAdmin) {
        this.id = id;
        this.descricao = descricao;
        this.moduloFinanceiro = moduloFinanceiro;
        this.moduloGestao = moduloGestao;
        this.moduloCaixa = moduloCaixa;
        this.moduloCozinha = moduloCozinha;
        this.moduloAtendente = moduloAtendente;
        this.moduloAdmin = moduloAdmin;
    }
    public Grupo(int id, String descricao, boolean moduloFinanceiro, boolean moduloGestao, boolean moduloCaixa, boolean moduloCozinha, boolean moduloAtendente, boolean moduloAdmin, Set usuarios) {
       this.id = id;
       this.descricao = descricao;
       this.moduloFinanceiro = moduloFinanceiro;
       this.moduloGestao = moduloGestao;
       this.moduloCaixa = moduloCaixa;
       this.moduloCozinha = moduloCozinha;
       this.moduloAtendente = moduloAtendente;
       this.moduloAdmin = moduloAdmin;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", nullable=false, length=60)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="modulo_financeiro", nullable=false)
    public boolean isModuloFinanceiro() {
        return this.moduloFinanceiro;
    }
    
    public void setModuloFinanceiro(boolean moduloFinanceiro) {
        this.moduloFinanceiro = moduloFinanceiro;
    }

    
    @Column(name="modulo_gestao", nullable=false)
    public boolean isModuloGestao() {
        return this.moduloGestao;
    }
    
    public void setModuloGestao(boolean moduloGestao) {
        this.moduloGestao = moduloGestao;
    }

    
    @Column(name="modulo_caixa", nullable=false)
    public boolean isModuloCaixa() {
        return this.moduloCaixa;
    }
    
    public void setModuloCaixa(boolean moduloCaixa) {
        this.moduloCaixa = moduloCaixa;
    }

    
    @Column(name="modulo_cozinha", nullable=false)
    public boolean isModuloCozinha() {
        return this.moduloCozinha;
    }
    
    public void setModuloCozinha(boolean moduloCozinha) {
        this.moduloCozinha = moduloCozinha;
    }

    
    @Column(name="modulo_atendente", nullable=false)
    public boolean isModuloAtendente() {
        return this.moduloAtendente;
    }
    
    public void setModuloAtendente(boolean moduloAtendente) {
        this.moduloAtendente = moduloAtendente;
    }

    
    @Column(name="modulo_admin", nullable=false)
    public boolean isModuloAdmin() {
        return this.moduloAdmin;
    }
    
    public void setModuloAdmin(boolean moduloAdmin) {
        this.moduloAdmin = moduloAdmin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupo")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


