package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ItemPedido generated by hbm2java
 */
public class ItemPedido  implements java.io.Serializable {


     private ItemPedidoId id;
     private Pedido pedido;
     private Produto produto;
     private BigDecimal valor;
     private int quantidade;
     private BigDecimal desconto;

    public ItemPedido() {
    }

	
    public ItemPedido(ItemPedidoId id, Pedido pedido, Produto produto, BigDecimal valor, int quantidade) {
        this.id = id;
        this.pedido = pedido;
        this.produto = produto;
        this.valor = valor;
        this.quantidade = quantidade;
    }
    public ItemPedido(ItemPedidoId id, Pedido pedido, Produto produto, BigDecimal valor, int quantidade, BigDecimal desconto) {
       this.id = id;
       this.pedido = pedido;
       this.produto = produto;
       this.valor = valor;
       this.quantidade = quantidade;
       this.desconto = desconto;
    }
   
    public ItemPedidoId getId() {
        return this.id;
    }
    
    public void setId(ItemPedidoId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }




}


