package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int id;
     private Entregador entregador;
     private Pessoa pessoa;
     private Usuario usuarioByCaixaId;
     private Usuario usuarioByAtendenteId;
     private Date dataHora;
     private Date dataHoraFechado;
     private BigDecimal valor;
     private Integer mesa;
     private String logradouro;
     private String bairro;
     private String complemento;
     private Integer numero;
     private Integer tempoDeslocamento;
     private Character status;
     private String observacao;
     private Set itemPedidos = new HashSet(0);
     private Set contasRecebers = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int id, Usuario usuarioByCaixaId, Usuario usuarioByAtendenteId, Date dataHora, BigDecimal valor) {
        this.id = id;
        this.usuarioByCaixaId = usuarioByCaixaId;
        this.usuarioByAtendenteId = usuarioByAtendenteId;
        this.dataHora = dataHora;
        this.valor = valor;
    }
    public Pedido(int id, Entregador entregador, Pessoa pessoa, Usuario usuarioByCaixaId, Usuario usuarioByAtendenteId, Date dataHora, Date dataHoraFechado, BigDecimal valor, Integer mesa, String logradouro, String bairro, String complemento, Integer numero, Integer tempoDeslocamento, Character status, String observacao, Set itemPedidos, Set contasRecebers) {
       this.id = id;
       this.entregador = entregador;
       this.pessoa = pessoa;
       this.usuarioByCaixaId = usuarioByCaixaId;
       this.usuarioByAtendenteId = usuarioByAtendenteId;
       this.dataHora = dataHora;
       this.dataHoraFechado = dataHoraFechado;
       this.valor = valor;
       this.mesa = mesa;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.complemento = complemento;
       this.numero = numero;
       this.tempoDeslocamento = tempoDeslocamento;
       this.status = status;
       this.observacao = observacao;
       this.itemPedidos = itemPedidos;
       this.contasRecebers = contasRecebers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Entregador getEntregador() {
        return this.entregador;
    }
    
    public void setEntregador(Entregador entregador) {
        this.entregador = entregador;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Usuario getUsuarioByCaixaId() {
        return this.usuarioByCaixaId;
    }
    
    public void setUsuarioByCaixaId(Usuario usuarioByCaixaId) {
        this.usuarioByCaixaId = usuarioByCaixaId;
    }
    public Usuario getUsuarioByAtendenteId() {
        return this.usuarioByAtendenteId;
    }
    
    public void setUsuarioByAtendenteId(Usuario usuarioByAtendenteId) {
        this.usuarioByAtendenteId = usuarioByAtendenteId;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }
    public Date getDataHoraFechado() {
        return this.dataHoraFechado;
    }
    
    public void setDataHoraFechado(Date dataHoraFechado) {
        this.dataHoraFechado = dataHoraFechado;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Integer getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Integer mesa) {
        this.mesa = mesa;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getTempoDeslocamento() {
        return this.tempoDeslocamento;
    }
    
    public void setTempoDeslocamento(Integer tempoDeslocamento) {
        this.tempoDeslocamento = tempoDeslocamento;
    }
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }
    public Set getContasRecebers() {
        return this.contasRecebers;
    }
    
    public void setContasRecebers(Set contasRecebers) {
        this.contasRecebers = contasRecebers;
    }




}


