package model;
// Generated Aug 13, 2018 9:27:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,schema="public"
)
public class Pessoa  implements java.io.Serializable {


     private long id;
     private Cidade cidade;
     private String nome;
     private String telefone1;
     private String telefone2;
     private String logradouro;
     private String bairro;
     private Integer numero;
     private String complemento;
     private String observacao;
     private boolean situacao;
     private Entregador entregador;
     private Set pedidos = new HashSet(0);
     private Funcionario funcionario;

    public Pessoa() {
    }

	
    public Pessoa(long id, String nome, boolean situacao) {
        this.id = id;
        this.nome = nome;
        this.situacao = situacao;
    }
    public Pessoa(long id, Cidade cidade, String nome, String telefone1, String telefone2, String logradouro, String bairro, Integer numero, String complemento, String observacao, boolean situacao, Entregador entregador, Set pedidos, Funcionario funcionario) {
       this.id = id;
       this.cidade = cidade;
       this.nome = nome;
       this.telefone1 = telefone1;
       this.telefone2 = telefone2;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.numero = numero;
       this.complemento = complemento;
       this.observacao = observacao;
       this.situacao = situacao;
       this.entregador = entregador;
       this.pedidos = pedidos;
       this.funcionario = funcionario;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_id")
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="nome", nullable=false, length=150)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="telefone1", length=50)
    public String getTelefone1() {
        return this.telefone1;
    }
    
    public void setTelefone1(String telefone1) {
        this.telefone1 = telefone1;
    }

    
    @Column(name="telefone2", length=50)
    public String getTelefone2() {
        return this.telefone2;
    }
    
    public void setTelefone2(String telefone2) {
        this.telefone2 = telefone2;
    }

    
    @Column(name="logradouro", length=150)
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    
    @Column(name="bairro", length=150)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    
    @Column(name="complemento", length=150)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="observacao", length=150)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="situacao", nullable=false)
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Entregador getEntregador() {
        return this.entregador;
    }
    
    public void setEntregador(Entregador entregador) {
        this.entregador = entregador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }




}


