package model;
// Generated 10/08/2018 00:28:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,schema="public"
)
public class Pessoa  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private Telefone telefone;
     private String nome;
     private String logradouro;
     private String bairro;
     private Integer numero;
     private String complemento;
     private String observacao;
     private boolean situacao;
     private Entregador entregador;
     private Set pedidos = new HashSet(0);
     private Funcionario funcionario;

    public Pessoa() {
    }

	
    public Pessoa(int id, Cidade cidade, Telefone telefone, String nome, boolean situacao) {
        this.id = id;
        this.cidade = cidade;
        this.telefone = telefone;
        this.nome = nome;
        this.situacao = situacao;
    }
    public Pessoa(int id, Cidade cidade, Telefone telefone, String nome, String logradouro, String bairro, Integer numero, String complemento, String observacao, boolean situacao, Entregador entregador, Set pedidos, Funcionario funcionario) {
       this.id = id;
       this.cidade = cidade;
       this.telefone = telefone;
       this.nome = nome;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.numero = numero;
       this.complemento = complemento;
       this.observacao = observacao;
       this.situacao = situacao;
       this.entregador = entregador;
       this.pedidos = pedidos;
       this.funcionario = funcionario;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_id", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="telefone_id", nullable=false)
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="nome", nullable=false, length=150)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="logradouro", length=150)
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    
    @Column(name="bairro", length=150)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    
    @Column(name="complemento", length=150)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="observacao", length=150)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="situacao", nullable=false)
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Entregador getEntregador() {
        return this.entregador;
    }
    
    public void setEntregador(Entregador entregador) {
        this.entregador = entregador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }




}


