package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int id;
     private Classificacao classificacao;
     private Fornecedor fornecedor;
     private String descricao;
     private BigDecimal valor;
     private int quantidade;
     private int tempoPreparo;
     private boolean cozinha;
     private int estoqueMinimo;
     private boolean insumo;
     private String unidadeMedida;
     private BigDecimal valorPromocao;
     private Date dataFimPromocao;
     private Set itemPedidos = new HashSet(0);
     private Set entradas = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int id, Classificacao classificacao, Fornecedor fornecedor, String descricao, BigDecimal valor, int quantidade, int tempoPreparo, boolean cozinha, int estoqueMinimo, boolean insumo) {
        this.id = id;
        this.classificacao = classificacao;
        this.fornecedor = fornecedor;
        this.descricao = descricao;
        this.valor = valor;
        this.quantidade = quantidade;
        this.tempoPreparo = tempoPreparo;
        this.cozinha = cozinha;
        this.estoqueMinimo = estoqueMinimo;
        this.insumo = insumo;
    }
    public Produto(int id, Classificacao classificacao, Fornecedor fornecedor, String descricao, BigDecimal valor, int quantidade, int tempoPreparo, boolean cozinha, int estoqueMinimo, boolean insumo, String unidadeMedida, BigDecimal valorPromocao, Date dataFimPromocao, Set itemPedidos, Set entradas) {
       this.id = id;
       this.classificacao = classificacao;
       this.fornecedor = fornecedor;
       this.descricao = descricao;
       this.valor = valor;
       this.quantidade = quantidade;
       this.tempoPreparo = tempoPreparo;
       this.cozinha = cozinha;
       this.estoqueMinimo = estoqueMinimo;
       this.insumo = insumo;
       this.unidadeMedida = unidadeMedida;
       this.valorPromocao = valorPromocao;
       this.dataFimPromocao = dataFimPromocao;
       this.itemPedidos = itemPedidos;
       this.entradas = entradas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Classificacao getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(Classificacao classificacao) {
        this.classificacao = classificacao;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public int getTempoPreparo() {
        return this.tempoPreparo;
    }
    
    public void setTempoPreparo(int tempoPreparo) {
        this.tempoPreparo = tempoPreparo;
    }
    public boolean isCozinha() {
        return this.cozinha;
    }
    
    public void setCozinha(boolean cozinha) {
        this.cozinha = cozinha;
    }
    public int getEstoqueMinimo() {
        return this.estoqueMinimo;
    }
    
    public void setEstoqueMinimo(int estoqueMinimo) {
        this.estoqueMinimo = estoqueMinimo;
    }
    public boolean isInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(boolean insumo) {
        this.insumo = insumo;
    }
    public String getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(String unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }
    public BigDecimal getValorPromocao() {
        return this.valorPromocao;
    }
    
    public void setValorPromocao(BigDecimal valorPromocao) {
        this.valorPromocao = valorPromocao;
    }
    public Date getDataFimPromocao() {
        return this.dataFimPromocao;
    }
    
    public void setDataFimPromocao(Date dataFimPromocao) {
        this.dataFimPromocao = dataFimPromocao;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


