package model;
// Generated 09/08/2018 21:15:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Grupo grupo;
     private String nome;
     private String senha;
     private boolean situacao;
     private Set auditorias = new HashSet(0);
     private Set pedidosForCaixaId = new HashSet(0);
     private Set pedidosForAtendenteId = new HashSet(0);
     private Set funcionarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, Grupo grupo, String nome, String senha, boolean situacao) {
        this.id = id;
        this.grupo = grupo;
        this.nome = nome;
        this.senha = senha;
        this.situacao = situacao;
    }
    public Usuario(int id, Grupo grupo, String nome, String senha, boolean situacao, Set auditorias, Set pedidosForCaixaId, Set pedidosForAtendenteId, Set funcionarios) {
       this.id = id;
       this.grupo = grupo;
       this.nome = nome;
       this.senha = senha;
       this.situacao = situacao;
       this.auditorias = auditorias;
       this.pedidosForCaixaId = pedidosForCaixaId;
       this.pedidosForAtendenteId = pedidosForAtendenteId;
       this.funcionarios = funcionarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }
    public Set getAuditorias() {
        return this.auditorias;
    }
    
    public void setAuditorias(Set auditorias) {
        this.auditorias = auditorias;
    }
    public Set getPedidosForCaixaId() {
        return this.pedidosForCaixaId;
    }
    
    public void setPedidosForCaixaId(Set pedidosForCaixaId) {
        this.pedidosForCaixaId = pedidosForCaixaId;
    }
    public Set getPedidosForAtendenteId() {
        return this.pedidosForAtendenteId;
    }
    
    public void setPedidosForAtendenteId(Set pedidosForAtendenteId) {
        this.pedidosForAtendenteId = pedidosForAtendenteId;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


