package view;

import controller.PessoaController;
import dao.MensagemRetorno;
import java.awt.Frame;
import java.io.File;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Pessoa;

/**
 *
 * @author
 */
public class JdEmail extends javax.swing.JFrame implements Pesquisavel {
    
    private PessoaController clienteController;
    private Pessoa pessoa;
    File[] Anexo;
    String Destinatarios;

    /**
     * Creates new form JanelaEmail
     */
    public JdEmail(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.clienteController = new PessoaController();
        this.pessoa = new Pessoa();
        EnderecoAnexo.setEditable(false);
        this.emailok.setVisible(false);
        this.total.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Destinatario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensagem = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        Assunto = new javax.swing.JTextField();
        EnderecoAnexo = new javax.swing.JTextField();
        NomeRemetente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BotaoExcluir = new javax.swing.JButton();
        BotaoAnexo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        emailok = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        btnNovo6 = new javax.swing.JButton();
        btnFechar6 = new javax.swing.JButton();
        btnPesquisar6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email");

        jPanel3.setPreferredSize(new java.awt.Dimension(786, 543));

        Destinatario.setText("email_destino@dominio.com.br");
        Destinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DestinatarioMouseClicked(evt);
            }
        });
        Destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinatarioActionPerformed(evt);
            }
        });

        Mensagem.setColumns(20);
        Mensagem.setLineWrap(true);
        Mensagem.setRows(5);
        Mensagem.setText("Digite sua Mensagem aqui.");
        Mensagem.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Mensagem);

        jLabel7.setText("Assunto");

        Assunto.setText("Digite aqui seu assunto");
        Assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssuntoActionPerformed(evt);
            }
        });

        EnderecoAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoAnexoActionPerformed(evt);
            }
        });

        NomeRemetente.setText("Linguini");
        NomeRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeRemetenteActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome");

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        BotaoAnexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotaoAnexo.setText("Anexo");
        BotaoAnexo.setToolTipText("");
        BotaoAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAnexoActionPerformed(evt);
            }
        });

        jLabel6.setText("Para");

        total.setText("0");

        emailok.setForeground(new java.awt.Color(0, 153, 51));
        emailok.setText("Email enviado com sucesso. Total:");

        jLabel8.setText("Selecionar todos clientes?");

        jCheckBox1.setText("Sim");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BotaoAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnderecoAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoExcluir))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                        .addComponent(emailok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Destinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                            .addComponent(Assunto))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(total)
                        .addComponent(emailok))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(NomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Assunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAnexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnderecoAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo6.setBackground(new java.awt.Color(51, 102, 255));
        btnNovo6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnNovo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-mais-48.png"))); // NOI18N
        btnNovo6.setText("Enviar");
        btnNovo6.setBorderPainted(false);
        btnNovo6.setContentAreaFilled(false);
        btnNovo6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo6ActionPerformed(evt);
            }
        });

        btnFechar6.setBackground(new java.awt.Color(51, 102, 255));
        btnFechar6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnFechar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-importar-48.png"))); // NOI18N
        btnFechar6.setText("Sair");
        btnFechar6.setBorderPainted(false);
        btnFechar6.setContentAreaFilled(false);
        btnFechar6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar6ActionPerformed(evt);
            }
        });

        btnPesquisar6.setBackground(new java.awt.Color(51, 102, 255));
        btnPesquisar6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnPesquisar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-pesquisar-48.png"))); // NOI18N
        btnPesquisar6.setText("Pesquisar");
        btnPesquisar6.setBorderPainted(false);
        btnPesquisar6.setContentAreaFilled(false);
        btnPesquisar6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnNovo6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnFechar6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFechar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPesquisar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(473, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAnexoActionPerformed
        
        JFileChooser file = new JFileChooser();
        file.setMultiSelectionEnabled(true);
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showOpenDialog(null);
        if (i == 1) {
            EnderecoAnexo.setText("");
            Anexo = null;
        } else {
            Anexo = file.getSelectedFiles();
            
            String SomaAnexo1 = "";
            String SomaAnexo2 = "";
            for (File enderec : Anexo) {
                EnderecoAnexo.setText(enderec.getPath());
                SomaAnexo1 = EnderecoAnexo.getText();
                SomaAnexo2 = SomaAnexo2 + SomaAnexo1 + ";";
                EnderecoAnexo.setText(SomaAnexo2);
                
            }
        }

    }//GEN-LAST:event_BotaoAnexoActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        EnderecoAnexo.setText("");
        Anexo = null;
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void AssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssuntoActionPerformed

    private void DestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinatarioActionPerformed

    private void DestinatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DestinatarioMouseClicked
        jdPesquisa pesquisa = new jdPesquisa((Frame) this.getParent(), this, true, this.clienteController);
        pesquisa.setLocationRelativeTo(pesquisa);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_DestinatarioMouseClicked

    private void EnderecoAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoAnexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoAnexoActionPerformed

    private void NomeRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeRemetenteActionPerformed

    private void btnNovo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo6ActionPerformed
        String[] dest = Destinatario.getText().split(",");
        for (int i = 0; i < dest.length; i++) {
            this.Destinatarios = dest[i];
            EmailAnexo();
            this.total.setText(dest.length + "");
        }
    }//GEN-LAST:event_btnNovo6ActionPerformed

    private void btnFechar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar6ActionPerformed
        dispose();
    }//GEN-LAST:event_btnFechar6ActionPerformed

    private void btnPesquisar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar6ActionPerformed

    }//GEN-LAST:event_btnPesquisar6ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (jCheckBox1.isSelected()) {
            this.Destinatario.setText("");
            this.Destinatario.setEnabled(false);
            MensagemRetorno msg = new MensagemRetorno();//this.clienteController.consultarTodosEmail();
            for (Object percorrer : msg.getLista()) {
                Pessoa p = (Pessoa) percorrer;
                if (p.getObservacao() != null) {
                    this.Destinatario.setText(this.Destinatario.getText() + p.getObservacao() + ",");
                }
            }            
        } else {
            this.Destinatario.setEnabled(true);
        }        
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Assunto;
    private javax.swing.JButton BotaoAnexo;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JTextField Destinatario;
    private javax.swing.JTextField EnderecoAnexo;
    private javax.swing.JTextArea Mensagem;
    private javax.swing.JTextField NomeRemetente;
    private javax.swing.JButton btnFechar6;
    private javax.swing.JButton btnNovo6;
    private javax.swing.JButton btnPesquisar6;
    private javax.swing.JLabel emailok;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

    public void EmailAnexo() {
        try {

            //usuario e senha do seu gmail
            final String usuario = "mupvplayer@gmail.com";
            final String senha = "olavinho11";

            //config. do gmail
            Properties mailProps = new Properties();
            mailProps.put("mail.transport.protocol", "smtp");
            mailProps.put("mail.smtp.starttls.enable", "true");
            //mailProps.put("mail.smtp.host", ServidorSMTP.getText());
            mailProps.put("mail.smtp.host", "smtp.gmail.com");
            mailProps.put("mail.smtp.auth", "true");
            //mailProps.put("mail.smtp.user", usuario);
            mailProps.put("mail.smtp.user", "mupvplayer@gmail.com");
            mailProps.put("mail.debug", "true");
            //mailProps.put("mail.smtp.port", Porta.getText());
            mailProps.put("mail.smtp.port", "465");
            //mailProps.put("mail.smtp.socketFactory.port", Porta.getText());
            mailProps.put("mail.smtp.socketFactory.port", "465");
            mailProps.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            mailProps.put("mail.smtp.socketFactory.fallback", "false");

            //eh necessario autenticar
            Session mailSession = Session.getInstance(mailProps, new Authenticator() {
                
                public PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(usuario, senha);
                }
            });
            mailSession.setDebug(false);

            //config. da mensagem
            Message mailMessage = new MimeMessage(mailSession);

            //remetente
            mailMessage.setFrom(new InternetAddress("mupvplayer@gmail.com", NomeRemetente.getText()));

            //destinatario
            //mailMessage.setRecipients(Message.RecipientType.TO, InternetAddress.parse(Destinatario.getText()));
            mailMessage.setRecipients(Message.RecipientType.TO, InternetAddress.parse(this.Destinatarios));

            //mensagem que vai no corpo do email
            MimeBodyPart mbpMensagem = new MimeBodyPart();
            mbpMensagem.setText(Mensagem.getText());

//			partes do email
            Multipart mp = new MimeMultipart();
            mp.addBodyPart(mbpMensagem);
            
            String Endereco_Anexo = "";
            if (Anexo != null) { // se tiver alguma coisa anexada ela inicializar o comando abaixo
                for (File element : Anexo) {
                    
                    Endereco_Anexo = element.getPath();
                    String imagem = Endereco_Anexo;
                    File Arquivo = new File(imagem);
                    //setando o anexo
                    MimeBodyPart mbpAnexo = new MimeBodyPart();
                    mbpAnexo.setDataHandler(new DataHandler(new FileDataSource(Arquivo)));
                    mbpAnexo.setFileName(Arquivo.getName());
                    mp.addBodyPart(mbpAnexo);
                }
            }

            //assunto do email
            mailMessage.setSubject(Assunto.getText());

            //seleciona o conteudo 
            mailMessage.setContent(mp);

            //envia o email
            Transport.send(mailMessage);
            //JOptionPane.showMessageDialog(null, "Email Enviado com Sucesso");
            this.emailok.setVisible(true);
            this.total.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Houve um erro no Envio !\n" + e);
        }
    }
    
    @Override
    public void carregar(int codigo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void limparCampos(int codigo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
