/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FornecedorController;
import dao.MensagemRetorno;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Fornecedor;
import utils.Formatacao;
import utils.Validacao;

/**
 *
 * @author VitinNote
 */
public class jdFornecedor extends javax.swing.JDialog implements Pesquisavel {

    private Fornecedor fornecedor;
    private FornecedorController fornecedorController;

    private void clearFields() {
        tfdCodigo.setText("");
        tfdNomeFantasia.setText("");
        tfdRazaoSocial.setText("");
        tffTelefone.setText("");
        tffCNPJ.setText("");
        this.fornecedor = new Fornecedor();
    }

    /**
     * Creates new form jdFornecedor
     */
    public jdFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.fornecedor = new Fornecedor();
        this.fornecedorController = new FornecedorController();
        Formatacao.formatarCnpj(tffCNPJ);
        Formatacao.formatarTelefone(tffTelefone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        tfdNomeFantasia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdRazaoSocial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tffCNPJ = new javax.swing.JFormattedTextField();
        tffTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedor");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setBackground(new java.awt.Color(0, 0, 204));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-mais-48.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.setContentAreaFilled(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(51, 102, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-salvar-48_1.png"))); // NOI18N
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(51, 102, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-excluir-48.png"))); // NOI18N
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(51, 102, 255));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-importar-48.png"))); // NOI18N
        btnFechar.setContentAreaFilled(false);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(51, 102, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-pesquisar-48.png"))); // NOI18N
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnNovo)
                .addGap(56, 56, 56)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(56, 56, 56)
                .addComponent(btnPesquisar)
                .addGap(56, 56, 56)
                .addComponent(btnFechar)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Código:");

        tfdCodigo.setEnabled(false);
        tfdCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCodigoActionPerformed(evt);
            }
        });

        tfdNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeFantasiaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome Fantasia:");

        tfdRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdRazaoSocialActionPerformed(evt);
            }
        });

        jLabel8.setText("Razão Social:");

        jLabel9.setText("CNPJ:");

        jLabel10.setText("Telefone:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tffCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tffCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        clearFields();
        //this.limparCampos((int) this.fornecedor.getId());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (Validacao.camposPreenchidos(camposObrigatorios())) {
            if (!Validacao.contarNumeros(tffTelefone.getText(), 10)) {
                JOptionPane.showMessageDialog(null, "Telefone inválido!");
                tffTelefone.setBackground(Color.yellow);
            } else if (!tfdCodigo.getText().equals("")) {
                this.fornecedor.setCnpj(Formatacao.removerFormatacao(tffCNPJ.getText()));
                this.fornecedor.setNomeFantasia(tfdNomeFantasia.getText());
                this.fornecedor.setRazaoSocial(tfdRazaoSocial.getText());
                this.fornecedor.setTelefone(Formatacao.removerFormatacao(tffTelefone.getText()));

                MensagemRetorno msg = this.fornecedorController.atualizar(this.fornecedor);
                System.out.println("atualizando");
                if (msg.isSucesso()) {
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
                    System.out.println(msg.getMensagem());

                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao atualizar", "ERRO!", JOptionPane.WARNING_MESSAGE);
                    System.out.println(msg.getMensagem());

                    clearFields();
                }
            } else {
                this.fornecedor.setCnpj(Formatacao.removerFormatacao(tffCNPJ.getText()));
                this.fornecedor.setNomeFantasia(tfdNomeFantasia.getText());
                this.fornecedor.setRazaoSocial(tfdRazaoSocial.getText());
                this.fornecedor.setSituacao(true);
                this.fornecedor.setTelefone(Formatacao.removerFormatacao(tffTelefone.getText()));

                MensagemRetorno msg = this.fornecedorController.salvar(this.fornecedor);
                if (msg.isSucesso()) {
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                    System.out.println(msg.getMensagem());

                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao salvar", "ERRO!", JOptionPane.WARNING_MESSAGE);
                    System.out.println(msg.getMensagem());

                    clearFields();
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!tfdCodigo.getText().equals("")) {
            MensagemRetorno msg = this.fornecedorController.consultarPorID(Integer.parseInt(tfdCodigo.getText()));
            this.fornecedor = (Fornecedor) msg.getObjeto();
            msg = this.fornecedorController.excluir(Integer.valueOf((int) fornecedor.getId()));
            if (msg.isSucesso()) {
                JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                System.out.println(msg.getMensagem());

                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao excluir", "ERRO!", JOptionPane.WARNING_MESSAGE);
                System.out.println(msg.getMensagem());

                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o fornecedor primeiro");
            System.out.println("selecione");
            jdPesquisa pesquisa = new jdPesquisa((Frame) this.getParent(), this, true, this.fornecedorController);
            pesquisa.setLocationRelativeTo(pesquisa);
            pesquisa.setVisible(true);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        jdPesquisa pesquisa = new jdPesquisa((Frame) this.getParent(), this, true, this.fornecedorController);
        pesquisa.setLocationRelativeTo(pesquisa);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfdCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCodigoActionPerformed

    }//GEN-LAST:event_tfdCodigoActionPerformed

    private void tfdNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeFantasiaActionPerformed

    private void tfdRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdRazaoSocialActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdNomeFantasia;
    private javax.swing.JTextField tfdRazaoSocial;
    private javax.swing.JFormattedTextField tffCNPJ;
    private javax.swing.JFormattedTextField tffTelefone;
    // End of variables declaration//GEN-END:variables

    private JTextField[] camposObrigatorios() {
        JTextField[] campos = {this.tfdNomeFantasia, this.tffTelefone};
        return campos;
    }

    @Override
    public void carregar(int codigo) {
        MensagemRetorno retorno = this.fornecedorController.consultarPorID(codigo);
        this.fornecedor = (Fornecedor) retorno.getObjeto();
        this.tfdCodigo.setText(this.fornecedor.getId() + "");
        this.tfdNomeFantasia.setText(this.fornecedor.getNomeFantasia());
        this.tfdRazaoSocial.setText(this.fornecedor.getRazaoSocial());
        this.tffCNPJ.setText(this.fornecedor.getCnpj());
        this.tffTelefone.setText(this.fornecedor.getTelefone());
    }

    @Override
    public void limparCampos(int codigo) {
        if (this.fornecedor.getId() == codigo) {
            //limpa campos da tela
            this.fornecedor = new Fornecedor();
            this.tfdCodigo.setText(this.fornecedor.getId() + "");
            this.tfdNomeFantasia.setText(this.fornecedor.getNomeFantasia());
            this.tfdRazaoSocial.setText(this.fornecedor.getRazaoSocial());
            this.tffCNPJ.setText(this.fornecedor.getCnpj());
            this.tffTelefone.setText(this.fornecedor.getTelefone());

        }
    }
}
