/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClassificacaoController;
import controller.FornecedorController;
import controller.ProdutoController;
import dao.GeradorLog;
import dao.MensagemRetorno;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Classificacao;
import model.Fornecedor;
import model.Produto;
import utils.Calendario;
import utils.ControlarEntradaNumero;
import utils.Formatacao;
import utils.Giba;
import utils.Validacao;

/**
 *
 * @author VitinNote
 */
public class jdProduto extends javax.swing.JDialog implements Pesquisavel {

    private Produto produto;
    private ProdutoController produtoController;
    private ClassificacaoController classificacaoController;
    private Classificacao classificacao;
    private Fornecedor fornecedor;
    private FornecedorController fornecedorController;
    private Calendario calendario;
    public static String nomeTela = "telaProduto";

    //A FAZER > VALOR VENDA SEMPRE MAIOR QUE CUSTO - VALIDAR
    //ADICIONAR CODIGO DE BARRAS NO BANCO
    /**
     * Creates new form jdProduto
     */
    public jdProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.btnSalvar.setName("btnSalvar");
        this.btnExcluir.setName("btnExcluir");
        this.btnPesquisar.setName("btnPesquisar");
        this.btnNovo.setName("btnNovo");
                
        this.produto = new Produto();
        this.produtoController = new ProdutoController();
        this.fornecedor = new Fornecedor();
        this.fornecedorController = new FornecedorController();
        this.classificacao = new Classificacao();
        this.classificacaoController = new ClassificacaoController();
        this.classificacaoController.popularCombo(this.comboCategoria);
        this.fornecedorController.popularCombo(this.comboFornecedor);
        this.calendario = new Calendario();

        //Campos Formatados
        Formatacao.formatarData(tffDataFimPromocao);
        tffDataFimPromocao.setEnabled(false);
        tfdEstoqueMinimo.setDocument(new ControlarEntradaNumero(5));
        tfdEstoque.setDocument(new ControlarEntradaNumero((5)));
        tfdTempoPreparo.setDocument(new ControlarEntradaNumero(5));

        //Iniciar préfixados
        this.produto.setCozinha(false);
        this.produto.setInsumo(false);
        rUnidade.setSelected(true);
        this.tfdEstoque.setText("0");
        this.tfdEstoqueMinimo.setText("0");
        this.tfdTempoPreparo.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoMedida = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        tfdNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfdCodigoBarras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rUnidade = new javax.swing.JRadioButton();
        rKilo = new javax.swing.JRadioButton();
        comboCategoria = new javax.swing.JComboBox<>();
        tffPrecoCusto = new apoio.MoedaFormatada();
        rLitro = new javax.swing.JRadioButton();
        comboFornecedor = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        tffPrecoVenda = new apoio.MoedaFormatada();
        jtabMais = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkItemCozinha = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboCozinha = new javax.swing.JComboBox<>();
        tfdTempoPreparo = new javax.swing.JFormattedTextField();
        checkInsumo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfdEstoque = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        tfdEstoqueMinimo = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        tffPrecoPromocao = new apoio.MoedaFormatada();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tffDataFimPromocao = new javax.swing.JFormattedTextField();
        checkInsumo1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setBackground(new java.awt.Color(0, 0, 204));
        btnNovo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(254, 254, 254));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-mais-48.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo");
        btnNovo.setContentAreaFilled(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(51, 102, 255));
        btnSalvar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(254, 254, 254));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-salvar-48_1.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(51, 102, 255));
        btnExcluir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(254, 254, 254));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-excluir-48.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(51, 102, 255));
        btnFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(254, 254, 254));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-importar-48.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setContentAreaFilled(false);
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(51, 102, 255));
        btnPesquisar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(254, 254, 254));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons8-pesquisar-48.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar)
                    .addComponent(btnFechar)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir))
                .addGap(0, 0, 0))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Código");

        tfdCodigo.setEnabled(false);
        tfdCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCodigoActionPerformed(evt);
            }
        });

        tfdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome*");

        jLabel8.setText("Categoria");

        jLabel9.setText("Preço de Venda*");

        jLabel10.setText("Preço de Custo*");

        tfdCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCodigoBarrasActionPerformed(evt);
            }
        });

        jLabel4.setText("Código Personalizado");

        jLabel11.setText("Medida");

        btnGrupoMedida.add(rUnidade);
        rUnidade.setText("UN");
        rUnidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rUnidadeItemStateChanged(evt);
            }
        });
        rUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUnidadeActionPerformed(evt);
            }
        });

        btnGrupoMedida.add(rKilo);
        rKilo.setText("KG");
        rKilo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rKiloItemStateChanged(evt);
            }
        });
        rKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKiloActionPerformed(evt);
            }
        });

        comboCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCategoriaItemStateChanged(evt);
            }
        });

        btnGrupoMedida.add(rLitro);
        rLitro.setText("LT");
        rLitro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rLitroItemStateChanged(evt);
            }
        });
        rLitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLitroActionPerformed(evt);
            }
        });

        comboFornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFornecedorItemStateChanged(evt);
            }
        });

        jLabel18.setText("Fornecedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)
                        .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(50, 50, 50)
                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(rUnidade)
                        .addGap(18, 18, 18)
                        .addComponent(rKilo)
                        .addGap(18, 18, 18)
                        .addComponent(rLitro)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)
                                .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(tffPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tffPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(rUnidade)
                    .addComponent(rKilo)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rLitro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(comboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tffPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel5.setText("Tempo de Preparo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel12.setText("- Visualizado no painel da cozinha. ");

        checkItemCozinha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkItemCozinha.setText("Item para cozinha");
        checkItemCozinha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkItemCozinhaItemStateChanged(evt);
            }
        });
        checkItemCozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkItemCozinhaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("- Em minutos.");

        jLabel6.setText("Selecione a Cozinha");

        comboCozinha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfdTempoPreparo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfdTempoPreparo.setText("0");
        tfdTempoPreparo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdTempoPreparoFocusLost(evt);
            }
        });

        checkInsumo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkInsumo.setText("Insumo");
        checkInsumo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkInsumoItemStateChanged(evt);
            }
        });
        checkInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(10, 10, 10)
                            .addComponent(tfdTempoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkInsumo)
                        .addGap(230, 230, 230))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkItemCozinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(checkItemCozinha))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(tfdTempoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkInsumo)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jtabMais.addTab("Mais Detalhes", jPanel3);

        jLabel16.setText("Estoque");

        tfdEstoque.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfdEstoque.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfdEstoqueCaretUpdate(evt);
            }
        });
        tfdEstoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEstoqueFocusLost(evt);
            }
        });
        tfdEstoque.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfdEstoquePropertyChange(evt);
            }
        });

        jLabel17.setText("Estoque Mínimo");

        tfdEstoqueMinimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfdEstoqueMinimo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEstoqueMinimoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(10, 10, 10)
                        .addComponent(tfdEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(621, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfdEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jtabMais.addTab("Estoque", jPanel4);

        tffPrecoPromocao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffPrecoPromocaoFocusLost(evt);
            }
        });
        tffPrecoPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffPrecoPromocaoActionPerformed(evt);
            }
        });

        jLabel14.setText("Preço na Promoção");

        jLabel15.setText("Data Fim da Promoção");

        tffDataFimPromocao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffDataFimPromocaoFocusLost(evt);
            }
        });
        tffDataFimPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffDataFimPromocaoActionPerformed(evt);
            }
        });

        checkInsumo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkInsumo1.setText("Item em promoção");
        checkInsumo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkInsumo1ItemStateChanged(evt);
            }
        });
        checkInsumo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInsumo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInsumo1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tffPrecoPromocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tffDataFimPromocao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(575, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(checkInsumo1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffPrecoPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tffDataFimPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jtabMais.addTab("Promoção", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtabMais, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtabMais)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        clearFields();
        //this.limparCampos((int) this.fornecedor.getId());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Calendario cal = new Calendario();

        if (btnGrupoMedida.isSelected(rKilo.getModel())) {

        }
        if (Validacao.camposPreenchidos(camposObrigatorios())) {
            if (!tfdCodigo.getText().equals("")) {
                this.produto.setDescricao(tfdNome.getText());
                this.produto.setEstoqueMinimo(Integer.parseInt(tfdEstoqueMinimo.getText()));
                this.produto.setQuantidade(Integer.parseInt(tfdEstoque.getText()));
                this.produto.setTempoPreparo(Integer.parseInt(tfdTempoPreparo.getText()));
                this.produto.setValorCusto(tffPrecoCusto.getValue());
                this.produto.setValorVenda(tffPrecoVenda.getValue());
                this.produto.setClassificacaoId(classificacao);
                this.produto.setFornecedorId(fornecedor);
                this.produto.setSituacao(true);

                MensagemRetorno msg = this.produtoController.atualizar(this.produto);
                if (msg.isSucesso()) {
                    msg.setMensagem("Atualizado com sucesso!");
                    JOptionPane.showMessageDialog(null, msg.getMensagem());
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Problemas ao atualizar registro!\n\n"
                            + "Mensagem técnica: \n" + msg.getMensagem());
                    new GeradorLog(msg.getMensagem());
                    clearFields();
                }
            } else {
                this.produto.setSituacao(true);
                this.produto.setDescricao(tfdNome.getText());
                this.produto.setEstoqueMinimo(Integer.parseInt(tfdEstoqueMinimo.getText()));
                this.produto.setQuantidade(Integer.parseInt(tfdEstoque.getText()));
                this.produto.setTempoPreparo(Integer.parseInt(tfdTempoPreparo.getText()));
                this.produto.setValorCusto(tffPrecoCusto.getValue());
                this.produto.setValorVenda(tffPrecoVenda.getValue());
                this.produto.setClassificacaoId(classificacao);
                this.produto.setFornecedorId(fornecedor);

                MensagemRetorno msg = this.produtoController.salvar(this.produto);
                if (msg.isSucesso()) {
                    JOptionPane.showMessageDialog(null, msg.getMensagem());
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Problemas ao salvar registro!\n\n"
                            + "Mensagem técnica: \n" + msg.getMensagem());
                    new GeradorLog(msg.getMensagem());
                    clearFields();
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!tfdCodigo.getText().equals("")) {
            MensagemRetorno msg = this.produtoController.consultarPorID(Integer.parseInt(tfdCodigo.getText()));
            this.produto = (Produto) msg.getObjeto();
            msg = this.produtoController.excluir(Integer.parseInt(produto.getId().toString()));
            if (msg.isSucesso()) {
                clearFields();
                JOptionPane.showMessageDialog(null, msg.getMensagem());

            } else {
                JOptionPane.showMessageDialog(null, "Problemas ao excluir registro!\n\n"
                        + "Mensagem técnica: \n" + msg.getMensagem());
                new GeradorLog(msg.getMensagem());
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para excluir");
            jdPesquisa pesquisa = new jdPesquisa((Frame) this.getParent(), this, true, this.produtoController);
            pesquisa.setLocationRelativeTo(pesquisa);
            pesquisa.setVisible(true);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        jdPesquisa pesquisa = new jdPesquisa((Frame) this.getParent(), this, true, this.produtoController);
        pesquisa.setLocationRelativeTo(pesquisa);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfdCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCodigoActionPerformed

    }//GEN-LAST:event_tfdCodigoActionPerformed

    private void tfdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeActionPerformed

    private void tfdCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdCodigoBarrasActionPerformed

    private void rUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUnidadeActionPerformed

    }//GEN-LAST:event_rUnidadeActionPerformed

    private void rKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rKiloActionPerformed

    private void rLitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLitroActionPerformed

    private void checkItemCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkItemCozinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkItemCozinhaActionPerformed

    private void tffPrecoPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffPrecoPromocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffPrecoPromocaoActionPerformed

    private void tffDataFimPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffDataFimPromocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffDataFimPromocaoActionPerformed

    private void checkInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInsumoActionPerformed

    private void comboCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCategoriaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int cod = ((ComboItens) comboCategoria.getSelectedItem()).getCodigo();
            if (cod != 0) {
                this.classificacao = (Classificacao) classificacaoController.consultarPorID(cod).getObjeto();
            }
        }
    }//GEN-LAST:event_comboCategoriaItemStateChanged

    private void checkItemCozinhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkItemCozinhaItemStateChanged
        if (checkItemCozinha.isSelected()) {
            this.produto.setCozinha(true);
        } else {
            this.produto.setCozinha(false);
        }
    }//GEN-LAST:event_checkItemCozinhaItemStateChanged

    private void tffDataFimPromocaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffDataFimPromocaoFocusLost
        Calendario cal = new Calendario();
        Date dataAtual = null;
        Date data = null;
        try {
            dataAtual = cal.getDateDeString(cal.obterDataAtualDMA());
            data = cal.getDateDeString(tffDataFimPromocao.getText());
        } catch (Exception ex) {
            Logger.getLogger(jdProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (data.after(dataAtual)) {
            this.produto.setDataFimPromocao(data);
            this.produto.setValorPromocao(tffPrecoPromocao.getValue());
        } else {
            JOptionPane.showMessageDialog(null, "Data inválida");

        }
    }//GEN-LAST:event_tffDataFimPromocaoFocusLost

    private void comboFornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFornecedorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int cod = ((ComboItens) comboFornecedor.getSelectedItem()).getCodigo();
            if (cod != 0) {
                this.fornecedor = (Fornecedor) fornecedorController.consultarPorID(cod).getObjeto();
            }
        }
    }//GEN-LAST:event_comboFornecedorItemStateChanged

    private void checkInsumoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkInsumoItemStateChanged
        if (checkInsumo.isSelected()) {
            this.produto.setInsumo(true);
        } else {
            this.produto.setInsumo(false);
        }
    }//GEN-LAST:event_checkInsumoItemStateChanged

    private void tfdTempoPreparoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdTempoPreparoFocusLost
        String trim = tfdTempoPreparo.getText().trim();
        if (trim.length() == 0) {
            tfdTempoPreparo.setText("0");
        }
    }//GEN-LAST:event_tfdTempoPreparoFocusLost

    private void tfdEstoqueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEstoqueFocusLost
        String trim = tfdEstoque.getText().trim();
        if (trim.length() == 0) {
            tfdEstoque.setText("0");
            //this.produto.setQuantidade(Integer.parseInt(tfdEstoque.getText()));
        }
    }//GEN-LAST:event_tfdEstoqueFocusLost

    private void tfdEstoqueMinimoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEstoqueMinimoFocusLost
        String trim = tfdEstoqueMinimo.getText().trim();
        if (trim.length() == 0) {
            tfdEstoqueMinimo.setText("0");
            //this.produto.setEstoqueMinimo(Integer.parseInt(tfdEstoqueMinimo.getText()));
        }
    }//GEN-LAST:event_tfdEstoqueMinimoFocusLost

    private void rUnidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rUnidadeItemStateChanged
        if (rUnidade.isSelected()) {
            this.produto.setUnidadeMedida("UN");
        }
    }//GEN-LAST:event_rUnidadeItemStateChanged

    private void rKiloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rKiloItemStateChanged
        if (rKilo.isSelected()) {
            this.produto.setUnidadeMedida("KG");
        }
    }//GEN-LAST:event_rKiloItemStateChanged

    private void rLitroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rLitroItemStateChanged
        if (rLitro.isSelected()) {
            this.produto.setUnidadeMedida("LT");
        }
    }//GEN-LAST:event_rLitroItemStateChanged

    private void tfdEstoquePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfdEstoquePropertyChange

    }//GEN-LAST:event_tfdEstoquePropertyChange

    private void tfdEstoqueCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfdEstoqueCaretUpdate

    }//GEN-LAST:event_tfdEstoqueCaretUpdate

    private void tffPrecoPromocaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffPrecoPromocaoFocusLost
        if (checkInsumo1.isSelected()) {
            this.produto.setValorPromocao(tffPrecoPromocao.getValue());
            try {
                this.produto.setDataFimPromocao(calendario.getDateDeString(tffDataFimPromocao.getText()));
            } catch (Exception ex) {
                Logger.getLogger(jdProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            tffPrecoPromocao.setText("");
            tffDataFimPromocao.setText("");
            this.produto.setValorPromocao(null);
            Date date = null;
            this.produto.setDataFimPromocao(date);
        }

        //        Calendario cal = new Calendario();
//        if (!tffPrecoPromocao.getText().equals("R$ 0,00")) {
//            tffDataFimPromocao.setText(cal.obterDataAtualMais(5));
//            try {
//                this.produto.setDataFimPromocao(cal.getDateDeString(tffDataFimPromocao.getText()));
//            } catch (Exception ex) {
//                Logger.getLogger(jdProduto.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            this.produto.setValorPromocao(tffPrecoPromocao.getValue());
//        } else {
//            tffDataFimPromocao.setText("");
//            tffPrecoPromocao.setText("");
//            try {
//                this.produto.setDataFimPromocao(cal.getDateDeString(tffDataFimPromocao.getText()));
//            } catch (Exception ex) {
//                Logger.getLogger(jdProduto.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

    }//GEN-LAST:event_tffPrecoPromocaoFocusLost

    private void checkInsumo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInsumo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInsumo1ActionPerformed

    private void checkInsumo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkInsumo1ItemStateChanged
        if (checkInsumo1.isSelected()) {
            calendario = new Calendario();
            tffDataFimPromocao.setText(calendario.obterDataAtualMais(1));
            tffDataFimPromocao.setEnabled(true);
            this.produto.setValorPromocao(tffPrecoPromocao.getValue());
            try {
                this.produto.setDataFimPromocao(calendario.getDateDeString(tffDataFimPromocao.getText()));
            } catch (Exception ex) {
                Logger.getLogger(jdProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            tffPrecoPromocao.setText("");
            tffDataFimPromocao.setText("");
            tffDataFimPromocao.setEnabled(false);
            this.produto.setValorPromocao(null);
            Date date = null;
            this.produto.setDataFimPromocao(date);
        }

    }//GEN-LAST:event_checkInsumo1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.ButtonGroup btnGrupoMedida;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkInsumo;
    private javax.swing.JCheckBox checkInsumo1;
    private javax.swing.JCheckBox checkItemCozinha;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboCozinha;
    private javax.swing.JComboBox<String> comboFornecedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jtabMais;
    private javax.swing.JRadioButton rKilo;
    private javax.swing.JRadioButton rLitro;
    private javax.swing.JRadioButton rUnidade;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdCodigoBarras;
    private javax.swing.JFormattedTextField tfdEstoque;
    private javax.swing.JFormattedTextField tfdEstoqueMinimo;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdTempoPreparo;
    private javax.swing.JFormattedTextField tffDataFimPromocao;
    private apoio.MoedaFormatada tffPrecoCusto;
    private apoio.MoedaFormatada tffPrecoPromocao;
    private apoio.MoedaFormatada tffPrecoVenda;
    // End of variables declaration//GEN-END:variables

    private JTextField[] camposObrigatorios() {
        JTextField[] campos = {this.tfdNome};
        if (this.tffPrecoCusto.getText().equals("R$ 0,00")) {
            this.tffPrecoCusto.setText("");
            JTextField[] campose = {this.tfdNome, this.tffPrecoCusto};
            campos = campose;
            System.out.println("PRECO CUSTO = NADA");
        }
//        if (this.produto.getUnidadeMedida().equals("")) {
//            this.produto.setUnidadeMedida("UN");
//        }

        return campos;
    }

    private void clearFields() {
        tfdCodigo.setText("");
        tfdNome.setText("");
        tffPrecoVenda.setText("");
        tfdCodigoBarras.setText("");
        tfdEstoque.setText("0");
        tfdEstoqueMinimo.setText("0");
        tfdTempoPreparo.setText("0");
        tffDataFimPromocao.setText("");
        tffPrecoCusto.setText("");
        tffPrecoPromocao.setText("");
        tffPrecoVenda.setText("");
        comboCategoria.setSelectedIndex(0);
        comboFornecedor.setSelectedIndex(0);
        checkInsumo.setSelected(false);
        checkItemCozinha.setSelected(false);
        checkInsumo1.setSelected(false);
        tffDataFimPromocao.setEditable(false);
        this.produto = new Produto();
    }

    @Override
    public void carregar(int codigo) {

        MensagemRetorno retorno = this.produtoController.consultarPorID(codigo);
        this.produto = (Produto) retorno.getObjeto();
        this.tfdCodigo.setText(this.produto.getId() + "");
        this.tfdNome.setText(this.produto.getDescricao() + "");
        this.comboCategoria.setSelectedIndex(this.produto.getClassificacaoId().getId().intValue());
        this.comboFornecedor.setSelectedIndex(this.produto.getFornecedorId().getId().intValue());
        if (this.produto.getUnidadeMedida().equals("UN ")) {
            rUnidade.setSelected(true);
        } else if (this.produto.getUnidadeMedida().equals("KG ")) {
            rKilo.setSelected(true);
        } else if (this.produto.getUnidadeMedida().equals("LT ")) {
            rLitro.setSelected(true);
        }
        this.tffPrecoCusto.setText(this.produto.getValorCusto().toString());
        this.tffPrecoVenda.setText(this.produto.getValorVenda().toString());
        if (!this.produto.getInsumo()) {
            this.checkInsumo.setSelected(false);
        } else {
            this.checkInsumo.setSelected(true);
        }
        if (!this.produto.getCozinha()) {
            this.checkItemCozinha.setSelected(false);
        } else {
            this.checkItemCozinha.setSelected(true);
        }
        this.tfdTempoPreparo.setText(this.produto.getTempoPreparo() + "");
        this.tfdEstoque.setText(this.produto.getQuantidade() + "");
        this.tfdEstoqueMinimo.setText(this.produto.getEstoqueMinimo() + "");
        if (this.produto.getValorPromocao() != null) {
            this.checkInsumo1.setSelected(true);
            this.tffDataFimPromocao.setEditable(true);
            this.tffPrecoPromocao.setText(this.produto.getValorPromocao().toString());
            Calendario c = new Calendario();
            this.tffDataFimPromocao.setText(c.getDataDeDate(this.produto.getDataFimPromocao()));

        } else {
            this.checkInsumo1.setSelected(false);
            this.tffPrecoPromocao.setText("0");
            this.tffDataFimPromocao.setText("");
        }

    }

    @Override
    public void limparCampos(int codigo) {
        if (this.produto.getId() == codigo) {
            //limpar campos da tela
            this.produto = new Produto();
            this.tfdCodigo.setText(this.produto.getId() + "");
            this.tfdNome.setText(this.produto.getDescricao());
        }
    }
}
